#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/tecno/KL5

PRODUCT_COPY_FILES += \
    vendor/tecno/KL5/proprietary/system_ext/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/kpoc_charger.rc \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/030b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030b0000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/030b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030b0000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/04010000000000000000000000003545.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/04010000000000000000000000003545.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07050000000000000000000000003545.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07050000000000000000000000003545.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07070000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07070000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07070000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08020000000000000000000000007169.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08020000000000000000000000007169.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08090000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08090000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/09010000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09010000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/09030000000000000000000000008270.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09030000000000000000000000008270.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin \
    vendor/tecno/KL5/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/configs/TranssionWM.json:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/configs/TranssionWM.json \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans3_SemiBold.otf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans3_SemiBold.otf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans_No3_3_Light.otf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans_No3_3_Light.otf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans_No3_4_Regular.otf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/HurmeGeometricSans_No3_4_Regular.otf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OFL.txt:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OFL.txt \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-Bold.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-Bold.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-ExtraBold.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-ExtraBold.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-Light.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-Light.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-Medium.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-Medium.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-Regular.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-Regular.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/OpenSans-SemiBold.ttf:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/OpenSans-SemiBold.ttf \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/ROBOTO-MEDIUM.TTF:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/ROBOTO-MEDIUM.TTF \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/fonts/ROBOTO-REGULAR.TTF:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/fonts/ROBOTO-REGULAR.TTF \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/+5g-L.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/+5g-L.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/+5g-S.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/+5g-S.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/5g-L.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/5g-L.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/5g-S.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/5g-S.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/GrayBackground.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/GrayBackground.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/KLBackground.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/KLBackground.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/Logo.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/Logo.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/RedPoint-kl.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/RedPoint-kl.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/RedPoint.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/RedPoint.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/blank-L.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/blank-L.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/blank-S.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/blank-S.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/blank.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/blank.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/gopro.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/gopro.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/logo-zero40-5g.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/logo-zero40-5g.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/logo-zero40-Flip.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/logo-zero40-Flip.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/goldwatermark/resources/icons/logo-zero40.svg:$(TARGET_COPY_OUT_VENDOR)/data/camera/goldwatermark/resources/icons/logo-zero40.svg \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_black_front.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_black_front.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_black_rear.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_black_rear.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_brown_front.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_brown_front.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_brown_rear.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_brown_rear.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_white_front.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_white_front.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Bright_white_rear.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Bright_white_rear.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Camon_front.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Camon_front.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/lut/colorEnhance/imgstyle_lut/Camon_rear.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/lut/colorEnhance/imgstyle_lut/Camon_rear.png \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/M_Segment_DoubleLoss_V1.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/M_Segment_DoubleLoss_V1.model \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/Transsion_Segment_Pre.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/Transsion_Segment_Pre.mnn \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/animal_human_landmark_fp16.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/animal_human_landmark_fp16.mnn \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/eyes_detect_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/eyes_detect_model \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/face_attribute.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/face_attribute.mnn \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facebeauty/ITD_model_1280_C24_QAT_pretrain.dla:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facebeauty/ITD_model_1280_C24_QAT_pretrain.dla \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facebeauty/ITD_model_1536_C24_QAT_pretrain.dla:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facebeauty/ITD_model_1536_C24_QAT_pretrain.dla \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facebeauty/ITD_model_768_C24_QAT_pretrain.dla:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facebeauty/ITD_model_768_C24_QAT_pretrain.dla \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facerecheck.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.bin \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facerecheck.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.param \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/facesr_hd_composite_ff_lite_4.0.13_mtkg52_ppl3_ocl_block.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facesr_hd_composite_ff_lite_4.0.13_mtkg52_ppl3_ocl_block.model \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5.tflite \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4.tflite \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/Paris06.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/Paris06.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/abao.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/abao.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/heijin01.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/heijin01.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/heijin02.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/heijin02.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/landiao.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/landiao.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/saibo.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/saibo.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/meishefilter/youhua.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/youhua.mslut \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/morpho_hdsr_tuning_params.xml:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/morpho_hdsr_tuning_params.xml \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/scene.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/scene.tflite \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/segment.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segment.tflite \
    vendor/tecno/KL5/proprietary/vendor/data/camera/model/segmentPre.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segmentPre.tflite \
    vendor/tecno/KL5/proprietary/vendor/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.bin \
    vendor/tecno/KL5/proprietary/vendor/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/detector/rf_newsshratio4_newresult_opt.param \
    vendor/tecno/KL5/proprietary/vendor/data/camera/tran_fd/tracker/det2.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/tracker/det2.bin \
    vendor/tecno/KL5/proprietary/vendor/data/camera/tran_fd/tracker/det2.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/tran_fd/tracker/det2.param \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_1280x720.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.nv21 \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_1280x720.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.yuyv \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_1920x1080.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.nv21 \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_1920x1080.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.yuyv \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_2560x1440.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.nv21 \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_2560x1440.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.yuyv \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_3840x2160.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.nv21 \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_3840x2160.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.yuyv \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_640x480.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.nv21 \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_640x480.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.yuyv \
    vendor/tecno/KL5/proprietary/vendor/data/camera/watermark/watermark_config:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_config \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.thermal_policy_00:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_00 \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.thermal_policy_03:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_03 \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.thermal_policy_05:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_05 \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/.thermal_policy_09:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_09 \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/tecno/KL5/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/tecno/KL5/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/SEC_THN31_FW_VTP.txt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/SEC_THN31_FW_VTP.txt.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/cache_hi5022q_17201891_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_hi5022q_17201891_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/cache_s5kjn1_17201892_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_s5kjn1_17201892_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/dgain_mask_hi5022q_17201891_back_g81.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_hi5022q_17201891_back_g81.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/dgain_mask_s5kjn1_17201892_back_g81.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_s5kjn1_17201892_back_g81.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/siq_ocl_cache_hi5022q_17201891_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_hi5022q_17201891_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/siq_ocl_cache_s5kjn1_17201892_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_s5kjn1_17201892_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/superiq_model_hi5022q_17201891_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_hi5022q_17201891_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/anc_siq/superiq_model_s5kjn1_17201892_back_g81:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_s5kjn1_17201892_back_g81 \
    vendor/tecno/KL5/proprietary/vendor/etc/apdb/APDB_MT6768_S01__W2426:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6768_S01__W2426 \
    vendor/tecno/KL5/proprietary/vendor/etc/apdb/APDB_MT6768_S01__W2426_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6768_S01__W2426_ENUM \
    vendor/tecno/KL5/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/preset_alarm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_alarm.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/preset_default.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_default.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/preset_music.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_music.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/preset_ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_ringtone.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/audio_param/preset_voip.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_voip.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/aurisys_config_fs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_fs.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/dar_thermal_core/thermal_core_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/dar_thermal_core/thermal_core_config.json \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/ecc_list_tran2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_tran2.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/firmware_slm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_slm.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/firmware_slm_ata.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_slm_ata.bin \
    vendor/tecno/KL5/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron-lazy.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.charger.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.charger.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.fmradio_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fmradio_drv.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/trustonic.mc_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.mc_kmsetkey_ca.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.focaltech.hardware.biometrics.fingerprint@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.focaltech.hardware.biometrics.fingerprint@1.0-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.goodix.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.goodix.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/tecno/KL5/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/tecno/KL5/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/power_app_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_app_cfg.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/power_app_fling_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_app_fling_cfg.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/powercontable.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powercontable.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/powerscntbl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerscntbl.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/tecno/KL5/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/tecno/KL5/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/tecno/KL5/proprietary/vendor/etc/wfd_source_capability.csv:$(TARGET_COPY_OUT_VENDOR)/etc/wfd_source_capability.csv \
    vendor/tecno/KL5/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/tecno/KL5/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_1a_1.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/tecno/KL5/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/tecno/KL5/proprietary/vendor/firmware/fs1599.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1599.fsm \
    vendor/tecno/KL5/proprietary/vendor/firmware/fs1801.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1801.fsm \
    vendor/tecno/KL5/proprietary/vendor/firmware/hdl_firmware_00.img:$(TARGET_COPY_OUT_VENDOR)/firmware/hdl_firmware_00.img \
    vendor/tecno/KL5/proprietary/vendor/firmware/hdl_firmware_01.img:$(TARGET_COPY_OUT_VENDOR)/firmware/hdl_firmware_01.img \
    vendor/tecno/KL5/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/tecno/KL5/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/tecno/KL5/proprietary/vendor/firmware/soc1_0_patch_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_1a_1_hdr.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/soc1_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1a_1_hdr.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/soc1_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_1a_1_hdr.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/soc1_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_1a_1_hdr.bin \
    vendor/tecno/KL5/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/tecno/KL5/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/tecno/KL5/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/tecno/KL5/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/tecno/KL5/proprietary/vendor/thh/ta/df1edda8627911e980ae507b9d9a7e7d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/df1edda8627911e980ae507b9d9a7e7d.ta

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    VP9SecureVdecCA \
    arm.graphics-V1-ndk_platform \
    android.hardware.bluetooth@1.1-impl-mediatek \
    android.hardware.thermal@2.0-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    libJpgEncPipe \
    libMtkOmxCore \
    libMtkSpeechEnh \
    libTEECommon \
    lib_speech_enh \
    libadpcmdec_mtk \
    libaedv \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libbwc \
    libcapctrl \
    libcodec2_mtk_c2store \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcustom_nvram \
    libcvsd_mtk \
    libfgauge_gm30 \
    libfile_op \
    libformatter \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libladder \
    libmp3dec_mtk \
    libmtcloader \
    libmtkcutils \
    libmtklimiter_vendor \
    libmtkproperty \
    libmtkrillog \
    libnvram \
    libnvram_sec \
    libstagefrighthw \
    libthha \
    libtneclient \
    libtranlog \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libverno \
    libvpu5 \
    libwo \
    libmtk_drvb \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    AVCSecureVencCA \
    audio.primary.mt6768 \
    audio.r_submix.mt6768 \
    libHEVCdec_sa.ca7.android \
    libMtkOmxAdpcmDec \
    libMtkOmxAlacDec \
    libMtkOmxApeDec \
    libMtkOmxGsmDec \
    libMtkOmxMp3Dec \
    lib_iir \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    consumerir.mt6768 \
    libaudiofmtconv \
    libaudiofoundation_kl5 \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libblisrc32_vendor \
    libfsmaudio \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libmsbc_mtk \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    librcs_interface \
    librcs_volte_core \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libthermalalgo \
    libvcodec_utility_v3a \
    libvcodecdrv_v3a \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpudv3a_vcodec \
    libvt_custom \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.rcs@2.0 \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    fake_serial_yuv_IdxMgr \
    fake_serial_yuv_tuning \
    gc08a8_mipi_raw_IdxMgr \
    gc08a8_mipi_raw_tuning \
    hi5022q_mipi_raw_IdxMgr \
    hi5022q_mipi_raw_tuning \
    hi846_mipi_raw_IdxMgr \
    hi846_mipi_raw_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    focal_fingerprint.default \
    fpsensor_fingerprint.default \
    gf_fingerprint.default \
    gps.default \
    hwcomposer.mt6768 \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    sensors.mt6768 \
    thermal_hal \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libImageEval \
    libMNN \
    libMNN_CL \
    libMNN_Express \
    libMNN_Vulkan \
    libMcClient \
    libNoFpsActor \
    libNvLutEffect \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcFilter \
    libTranArcHDR \
    libTranArcLLHDR \
    libTranColorEnhance \
    libTranDenoise \
    libTranExtImgProc \
    libTranExtImgThread \
    libTranEyeDetect \
    libTranFaceDetectCoordinate \
    libTranGenderDetect \
    libTranGoldWaterMark \
    libTranHumanLight \
    libTranITDFaceBeauty \
    libTranMSFilter \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranSmartDetection \
    libTranSuperResolution \
    libTranVideoSupeNightYuv \
    libTran_Log \
    libTran_mtkPowerAPI \
    libTranfacFunction \
    libTranfacOverlay \
    libWaterMarkProc \
    lib_bsscore \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libabfadp \
    libaipe_bokeh \
    libamipengine \
    libanc_hdr \
    libanc_hdr_adapter_hi5022q_17201891_back_g81 \
    libanc_hdr_adapter_s5kjn1_17201892_back_g81 \
    libancbase \
    libancbase_848 \
    libapmonitor_vendor \
    libappgamepq \
    libapu_mdw \
    libapusys \
    libapusys_edma \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libc++_shared \
    libcalculatesharpness \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lsctbl \
    libcam.hal3a.v3.nvram \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3_tranelapsedtime \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcamalgo.3dnr \
    libcamalgo.abf \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.utility \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera2ndk_vendor \
    libcameracustom.eis \
    libcameracustom.plugin \
    libcameracustom \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcolorenhance_64 \
    libcomposer_ext \
    libconnfem \
    libcurl_xcap_md \
    libdecrypt \
    libdenoise \
    libdre \
    libeffecthal.base \
    libeyedetector \
    libfacedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libfp_ext_svc2 \
    libgamehdr \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libheichal \
    libhwm \
    libicd_decoder \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimsg_log \
    libitdfacebeauty \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmfllcore \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmorpho_HDSR \
    libmpbase \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtk_bsg \
    libmtkares \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.thread \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_dpe \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_config_data \
    libneuroeara \
    libneuron_adapter \
    libneuron_platform \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    liboemcrypto \
    libportrait_repair_ppl3_ocl \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libpqpconfig \
    libqmc6308_kl5 \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    librilfusion \
    librmsclib1 \
    librpc \
    libsegmention \
    libsegmentionPre \
    libsensor_custom \
    libskhynix_q2b_5022Q_shared \
    libsmartdetector \
    libst_mobile \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libtf_asd_lib \
    libtflite_mtk \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtlcWidevineModularDrm \
    libtnev \
    libtrancamJsonConvertor \
    libtrancam_filelockmgr \
    libtranssion_bodybeauty \
    libtranssion_forkexecwrap \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libutinterface_custom_md \
    libutinterface_md \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libwatermark \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libyuvenhance \
    libdrmclearkeyplugin \
    libwvdrmengine \
    libdpframework \
    libnir_neon_driver \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    pblcfake_serial_yuv_IdxMgr \
    pblcfake_serial_yuv_tuning \
    pblcgc08a8_mipi_raw_IdxMgr \
    pblcgc08a8_mipi_raw_tuning \
    pblchi5022q_mipi_raw_IdxMgr \
    pblchi5022q_mipi_raw_tuning \
    pblchi846_mipi_raw_IdxMgr \
    pblchi846_mipi_raw_tuning \
    pblcs5kjn1_mipi_raw_IdxMgr \
    pblcs5kjn1_mipi_raw_tuning \
    s5kjn1_mipi_raw_IdxMgr \
    s5kjn1_mipi_raw_tuning \
    vendor.fpsensor.hardware.fpsensorhidlsvc@2.0 \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.transsion.hardware.tne.tneengine@1.0 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libdrm_system_ext \
    libshowlogo \
    libtranshowlogo \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.neuralnetworks@1.3-service-mtk-gpu.xml \
    android.hardware.usb@1.2-service-mediatekv2.xml \
    android.hardware.wifi.supplicant_hidl.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_2_default.xml \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.trustonic \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron-lazy \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.usb@1.2-service-mediatekv2 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.focaltech.hardware.biometrics.fingerprint@1.0-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    wpa_supplicant \
    ipsec_mon \
    kmsetkey_ca.trustonic \
    mcDriverDaemon \
    mnld \
    mtk_agpsd \
    netdagent \
    netdc \
    nvram_daemon \
    rcs_volte_stack \
    thermal \
    thermal_manager \
    thermalloadalgod \
    v3avpud \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wfca \
    wlan_assistant \
    wmt_launcher \
    wmt_loader \
    wpa_cli \
    kpoc_charger 

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_media_c2@1_2-mediatek \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_hw_vulkan_mt6768_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_prot_so
